services:
  client:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
    volumes:
      - ./config.js:/app/config.js
      - ./mirasaki-music-bot.db:/app/mirasaki-music-bot.db
